// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dev/unmango/v1alpha1/versions.proto (package dev.unmango.v1alpha1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file dev/unmango/v1alpha1/versions.proto.
 */
export const file_dev_unmango_v1alpha1_versions: GenFile = /*@__PURE__*/
  fileDesc(
    "CiNkZXYvdW5tYW5nby92MWFscGhhMS92ZXJzaW9ucy5wcm90bxIUZGV2LnVubWFuZ28udjFhbHBoYTEiGgoHVmVyc2lvbhIPCgd2ZXJzaW9uGAEgASgJIg0KC0xpc3RSZXF1ZXN0Ij8KDExpc3RSZXNwb25zZRIvCgh2ZXJzaW9ucxgBIAMoCzIdLmRldi51bm1hbmdvLnYxYWxwaGExLlZlcnNpb24yYAoPVmVyc2lvbnNTZXJ2aWNlEk0KBExpc3QSIS5kZXYudW5tYW5nby52MWFscGhhMS5MaXN0UmVxdWVzdBoiLmRldi51bm1hbmdvLnYxYWxwaGExLkxpc3RSZXNwb25zZULzAQoYY29tLmRldi51bm1hbmdvLnYxYWxwaGExQg1WZXJzaW9uc1Byb3RvUAFaVmdpdGh1Yi5jb20vdW5zdG9wcGFibGVtYW5nby9taW5lY3JhZnQtbWFuYWdlci9hcGkvZGV2L3VubWFuZ28vdjFhbHBoYTE7dW5tYW5nb3YxYWxwaGExogIDRFVYqgIURGV2LlVubWFuZ28uVjFhbHBoYTHKAhREZXZcVW5tYW5nb1xWMWFscGhhMeICIERldlxVbm1hbmdvXFYxYWxwaGExXEdQQk1ldGFkYXRh6gIWRGV2OjpVbm1hbmdvOjpWMWFscGhhMWIGcHJvdG8z",
  );

/**
 * @generated from message dev.unmango.v1alpha1.Version
 */
export type Version = Message<"dev.unmango.v1alpha1.Version"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;
};

/**
 * Describes the message dev.unmango.v1alpha1.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
export const VersionSchema: GenMessage<Version> = /*@__PURE__*/
  messageDesc(file_dev_unmango_v1alpha1_versions, 0);

/**
 * @generated from message dev.unmango.v1alpha1.ListRequest
 */
export type ListRequest = Message<"dev.unmango.v1alpha1.ListRequest"> & {};

/**
 * Describes the message dev.unmango.v1alpha1.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_dev_unmango_v1alpha1_versions, 1);

/**
 * @generated from message dev.unmango.v1alpha1.ListResponse
 */
export type ListResponse = Message<"dev.unmango.v1alpha1.ListResponse"> & {
  /**
   * @generated from field: repeated dev.unmango.v1alpha1.Version versions = 1;
   */
  versions: Version[];
};

/**
 * Describes the message dev.unmango.v1alpha1.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_dev_unmango_v1alpha1_versions, 2);

/**
 * @generated from service dev.unmango.v1alpha1.VersionsService
 */
export const VersionsService: GenService<{
  /**
   * @generated from rpc dev.unmango.v1alpha1.VersionsService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  };
}> = /*@__PURE__*/
  serviceDesc(file_dev_unmango_v1alpha1_versions, 0);
