// @generated by protoc-gen-es v2.2.0 with parameter "target=ts,import_extension=none"
// @generated from file dev/unmango/v1alpha1/versions.proto (package dev.unmango.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dev/unmango/v1alpha1/versions.proto.
 */
export const file_dev_unmango_v1alpha1_versions: GenFile = /*@__PURE__*/
  fileDesc("CiNkZXYvdW5tYW5nby92MWFscGhhMS92ZXJzaW9ucy5wcm90bxIUZGV2LnVubWFuZ28udjFhbHBoYTEiDQoLTGlzdFJlcXVlc3QiDgoMTGlzdFJlc3BvbnNlMmAKD1ZlcnNpb25zU2VydmljZRJNCgRMaXN0EiEuZGV2LnVubWFuZ28udjFhbHBoYTEuTGlzdFJlcXVlc3QaIi5kZXYudW5tYW5nby52MWFscGhhMS5MaXN0UmVzcG9uc2VC7wEKGGNvbS5kZXYudW5tYW5nby52MWFscGhhMUINVmVyc2lvbnNQcm90b1ABWlJnaXRodWIuY29tL3Vuc3RvcHBhYmxlbWFuZ28vbWluZWNyYWZ0LW1hbmFnZXIvZGV2L3VubWFuZ28vdjFhbHBoYTE7dW5tYW5nb3YxYWxwaGExogIDRFVYqgIURGV2LlVubWFuZ28uVjFhbHBoYTHKAhREZXZcVW5tYW5nb1xWMWFscGhhMeICIERldlxVbm1hbmdvXFYxYWxwaGExXEdQQk1ldGFkYXRh6gIWRGV2OjpVbm1hbmdvOjpWMWFscGhhMWIGcHJvdG8z");

/**
 * @generated from message dev.unmango.v1alpha1.ListRequest
 */
export type ListRequest = Message<"dev.unmango.v1alpha1.ListRequest"> & {
};

/**
 * Describes the message dev.unmango.v1alpha1.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_dev_unmango_v1alpha1_versions, 0);

/**
 * @generated from message dev.unmango.v1alpha1.ListResponse
 */
export type ListResponse = Message<"dev.unmango.v1alpha1.ListResponse"> & {
};

/**
 * Describes the message dev.unmango.v1alpha1.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_dev_unmango_v1alpha1_versions, 1);

/**
 * @generated from service dev.unmango.v1alpha1.VersionsService
 */
export const VersionsService: GenService<{
  /**
   * @generated from rpc dev.unmango.v1alpha1.VersionsService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dev_unmango_v1alpha1_versions, 0);

