// @generated by protobuf-ts 2.9.6 with parameter optimize_code_size
// @generated from protobuf file "dev/unmango/v1alpha1/versions.proto" (package "dev.unmango.v1alpha1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message dev.unmango.v1alpha1.ListRequest
 */
export interface ListRequest {
}
/**
 * @generated from protobuf message dev.unmango.v1alpha1.ListResponse
 */
export interface ListResponse {
}
// @generated message type with reflection information, may provide speed optimized methods
class ListRequest$Type extends MessageType<ListRequest> {
    constructor() {
        super("dev.unmango.v1alpha1.ListRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message dev.unmango.v1alpha1.ListRequest
 */
export const ListRequest = new ListRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListResponse$Type extends MessageType<ListResponse> {
    constructor() {
        super("dev.unmango.v1alpha1.ListResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message dev.unmango.v1alpha1.ListResponse
 */
export const ListResponse = new ListResponse$Type();
/**
 * @generated ServiceType for protobuf service dev.unmango.v1alpha1.VersionsService
 */
export const VersionsService = new ServiceType("dev.unmango.v1alpha1.VersionsService", [
    { name: "List", options: {}, I: ListRequest, O: ListResponse }
]);
