/**
 * @fileoverview gRPC-Web generated client stub for dev.unmango.v1alpha1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: dev/unmango/v1alpha1/versions.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as dev_unmango_v1alpha1_versions_pb from '../../../dev/unmango/v1alpha1/versions_pb'; // proto import: "dev/unmango/v1alpha1/versions.proto"


export class VersionsServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorList = new grpcWeb.MethodDescriptor(
    '/dev.unmango.v1alpha1.VersionsService/List',
    grpcWeb.MethodType.UNARY,
    dev_unmango_v1alpha1_versions_pb.ListRequest,
    dev_unmango_v1alpha1_versions_pb.ListResponse,
    (request: dev_unmango_v1alpha1_versions_pb.ListRequest) => {
      return request.serializeBinary();
    },
    dev_unmango_v1alpha1_versions_pb.ListResponse.deserializeBinary
  );

  list(
    request: dev_unmango_v1alpha1_versions_pb.ListRequest,
    metadata?: grpcWeb.Metadata | null): Promise<dev_unmango_v1alpha1_versions_pb.ListResponse>;

  list(
    request: dev_unmango_v1alpha1_versions_pb.ListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: dev_unmango_v1alpha1_versions_pb.ListResponse) => void): grpcWeb.ClientReadableStream<dev_unmango_v1alpha1_versions_pb.ListResponse>;

  list(
    request: dev_unmango_v1alpha1_versions_pb.ListRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: dev_unmango_v1alpha1_versions_pb.ListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/dev.unmango.v1alpha1.VersionsService/List',
        request,
        metadata || {},
        this.methodDescriptorList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/dev.unmango.v1alpha1.VersionsService/List',
    request,
    metadata || {},
    this.methodDescriptorList);
  }

}

