// @generated by protobuf-ts 2.9.6 with parameter optimize_code_size
// @generated from protobuf file "dev/unmango/v1alpha1/versions.proto" (package "dev.unmango.v1alpha1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { VersionsService } from "./versions";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListResponse } from "./versions";
import type { ListRequest } from "./versions";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service dev.unmango.v1alpha1.VersionsService
 */
export interface IVersionsServiceClient {
    /**
     * @generated from protobuf rpc: List(dev.unmango.v1alpha1.ListRequest) returns (dev.unmango.v1alpha1.ListResponse);
     */
    list(input: ListRequest, options?: RpcOptions): UnaryCall<ListRequest, ListResponse>;
}
/**
 * @generated from protobuf service dev.unmango.v1alpha1.VersionsService
 */
export class VersionsServiceClient implements IVersionsServiceClient, ServiceInfo {
    typeName = VersionsService.typeName;
    methods = VersionsService.methods;
    options = VersionsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: List(dev.unmango.v1alpha1.ListRequest) returns (dev.unmango.v1alpha1.ListResponse);
     */
    list(input: ListRequest, options?: RpcOptions): UnaryCall<ListRequest, ListResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRequest, ListResponse>("unary", this._transport, method, opt, input);
    }
}
