apiVersion: v1
kind: Pod
metadata:
  name: dev-container
spec:
  containers:
    - name: dev
      image: oven/bun:1.2.4-slim
      command: [bash, -c, 'bun install && bun dev']
      workingDir: /src
      ports:
        - containerPort: 6969
          hostPort: 6969
          name: http
      volumeMounts:
        - mountPath: /src
          name: src
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
  volumes:
    - name: src
      hostPath:
        path: /src
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-container
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-container
rules:
  - apiGroups:
      - shulkermc.io
    resources:
      - minecraftclusters
      - minecraftserverfleets
      - minecraftservers
      - proxyfleets
    verbs: [get, list, watch, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-container
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-container
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: dev-container
    namespace: default
