apiVersion: v1
kind: Pod
metadata:
  name: dev-container
spec:
  containers:
    - name: dev
      image: oven/bun:1.2.4-slim
      command: [bash, -c, 'bun install && bun dev']
      workingDir: /src
      ports:
        - containerPort: 3000
          hostPort: 3000
          name: http
      volumeMounts:
        - mountPath: /src
          name: src
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
  volumes:
    - name: src
      hostPath:
        path: /src
